# Generated by Django 4.2.30 on 2026-07-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nexus', '0001_initial'),
        ('omega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omega.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.subject')),
            ],
            options={
                'unique_together': {('day', 'period', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_term', models.IntegerField(choices=[(1, 'Mid 1'), (2, 'Mid 2')])),
                ('q1', models.FloatField(blank=True, null=True)),
                ('q2', models.FloatField(blank=True, null=True)),
                ('q3', models.FloatField(blank=True, null=True)),
                ('q4', models.FloatField(blank=True, null=True)),
                ('q5', models.FloatField(blank=True, null=True)),
                ('q6', models.FloatField(blank=True, null=True)),
                ('unit_test', models.FloatField(blank=True, null=True)),
                ('assignment', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexus.subject')),
            ],
            options={
                'unique_together': {('subject', 'student', 'mid_term')},
            },
        ),
    ]
